__include__: [
  '../dataset/cv_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

output_dir: ./output/advanced_rtdetrv2_r50vd_m_7x_coco


HybridEncoder:
  expansion: 0.5


RTDETRTransformerv2:
  eval_idx: 2 # use 3th decoder layer to eval


epoches: 84 # base
# epoches: 100 #for more tuning

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001 # base
      # lr: 0.000005 # for fine tuning purposes
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001 # base
  # lr: 0.00005 # for fine tuning purposes
  betas: [0.9, 0.999]
  weight_decay: 0.0001


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 81 # base
        # epoch: 90
  collate_fn:
    stop_epoch: 81 # base
    # stop_epoch: 90
